// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// truncate.cpp
cpp11::strings byte_trunc_(cpp11::strings string, long long unsigned int size);
extern "C" SEXP _bytetrunc2_byte_trunc_(SEXP string, SEXP size) {
  BEGIN_CPP11
    return cpp11::as_sexp(byte_trunc_(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(string), cpp11::as_cpp<cpp11::decay_t<long long unsigned int>>(size)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_bytetrunc2_byte_trunc_", (DL_FUNC) &_bytetrunc2_byte_trunc_, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_bytetrunc2(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
